# Base image
FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    tini \
    iptables \
    iputils-ping \
    tcpdump \
    frr \
    traceroute \
    isc-dhcp-server

# Force iptables to use nft backend
RUN update-alternatives --set iptables /usr/sbin/iptables-nft \
 && update-alternatives --set ip6tables /usr/sbin/ip6tables-nft

RUN mkdir -p /etc/frr /var/run/frr /run/frr /var/log/frr
RUN touch /etc/frr/ripd.conf /etc/frr/vtysh.conf /etc/frr/zebra.conf /etc/frr/ospfd.conf \
 && touch /var/log/frr/ripd.log /var/log/frr/vtysh.log /var/log/frr/zebra.log \
         /var/log/frr/ospfd.log /var/log/frr/mgmtd.log /var/log/frr/frr.log \
 && chown frr:frr /var/log/frr/* /run/frr

RUN ln -s /usr/lib/frr/zebra  /usr/sbin/zebra \
 && ln -s /usr/lib/frr/ripd   /usr/sbin/ripd \
 && ln -s /usr/lib/frr/ospfd  /usr/sbin/ospfd \
 && ln -s /usr/lib/frr/mgmtd  /usr/sbin/mgmtd

RUN echo "zebra=yes"  >  /etc/frr/daemons \
 && echo "mgmtd=yes" >> /etc/frr/daemons \
 && echo "ripd=yes"  >> /etc/frr/daemons \
 && echo "ospfd=yes" >> /etc/frr/daemons

COPY net-config /usr/local/bin/net-config
RUN chmod +x /usr/local/bin/net-config/*

ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["tail", "-f", "/dev/null"]
