# Base image
FROM alpine:latest

# Utilities for service implementation and testing
RUN apk add --no-cache iputils tcpdump bash wireguard-tools iproute2 gettext

COPY net-config /usr/local/bin/net-config
RUN chmod +x /usr/local/bin/net-config/*

# Set entrypoint to keep container running
CMD ["tail", "-f", "/dev/null"]
