# Base image
FROM alpine:latest

# Utilities for testing and demonstrations
RUN apk add --no-cache iputils tcpdump python3 py3-pip bash wireguard-tools iproute2 && \
    pip3 install --break-system-packages scapy

COPY net-config /usr/local/bin/net-config
RUN chmod +x /usr/local/bin/net-config/*

# Set entrypoint to keep container running
CMD ["tail", "-f", "/dev/null"]
