[Interface]
PrivateKey = 2P15hu32otP5BAev6SsnqeY4PMNhslfLEoFhJRx6pk0=
Address = 10.8.0.2/24

[Peer]
PublicKey = f5o1tDao6/eEgs54pdxWyLRxmgWTCR3/ENiixX2Hw3E=
AllowedIPs = 10.8.0.0/24
Endpoint = 192.168.3.3:51820
PersistentKeepalive = 25
