[Interface]
PrivateKey = AD53fIF2hTFYKBueG7vq053y8R2ozlLL1Kk+SPxR7Xc=
Address = 10.8.0.2/24

[Peer]
PublicKey = xw4Gu9zfU7W37Uhqzl2JVB03gQPJyLgVKCZtBwyAwVQ=
AllowedIPs = 10.8.0.0/24
Endpoint = 192.168.3.3:51820
PersistentKeepalive = 25
