[Interface]
PrivateKey = gOlcVDYkeJ6oT/y6nBKu06kwmTLRgtiSCeQynNJHgWg=
Address = 10.8.0.3/24

[Peer]
PublicKey = xw4Gu9zfU7W37Uhqzl2JVB03gQPJyLgVKCZtBwyAwVQ=
AllowedIPs = 10.8.0.0/24
Endpoint = 192.168.3.3:51820
PersistentKeepalive = 25
