CREATE DATABASE IF NOT EXISTS webapp;

CREATE USER IF NOT EXISTS 'user'@'192.168.4.%' IDENTIFIED BY 'user';
GRANT ALL PRIVILEGES ON webapp.* TO 'user'@'192.168.4.%';

FLUSH PRIVILEGES;

USE webapp;

CREATE TABLE IF NOT EXISTS visits (
    id INT AUTO_INCREMENT PRIMARY KEY,
    source_ip VARCHAR(45) NOT NULL,
    visited_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
