# Global parameters 
default-lease-time 43200;  # 12 hours
max-lease-time 86400;      # 24 hours max
authoritative;             
 
# Subnet N1
subnet 192.168.1.0 netmask 255.255.255.0 {
    range 192.168.1.10 192.168.1.100;   # Ip range
    option routers 192.168.1.1;         # Gateway
    option subnet-mask 255.255.255.0;
    option broadcast-address 192.168.1.255;
}
